### ISSUE TITLE
Error with webhosting

### ISSUE THREAD

**Issue by anespo** [Krxtopher/sumerian-host-demos-babylonjs#1]
Hi Kris,

I am trying to deploy in my EC2 instance and copied all the src files in /var/www/html but the problem is in the console I have this error:
`Uncaught TypeError: Failed to resolve module specifier "@amazon-sumerian-hosts/babylon". Relative references must start with either "/", "./", or "../".`
and the page still in loading
Thanks
Tony

**Comment by Krxtopher** [comment]
That indicates to me that you probably deployed the wrong set of files. If you deployed the files found in the `src/` directory of the repository you would see that error. You should instead be deploying the files found in the `dist/` directory that is created as the result of running `npm run build`.

**Comment by Krxtopher** [comment]
BTW, I've deployed these demos to my own public web server. Feel free to use and share the link with others if it would be helpful. https://dev.d3k4fnlmftnmcg.amplifyapp.com/

**Comment by anespo** [comment]
Thank you very much Kris -- It was my issue, last night was very late and I exchanged the content of /src instead of /dist. Now I see the host but I have an issue with the message:
"The browser has disabled microphone access for this website. Please update your browser preferences to allow microphone access. Then, reload this page."
The console log is 
`GEThttp://digitalhumans.click/favicon.ico
[HTTP/1.1 404 Not Found 0ms]

WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER. thinEngine.js:617
WebGL warning: generateMipmap: Tex image TEXTURE_CUBE_MAP_POSITIVE_X level 0 is incurring lazy initialization.
WebGL warning: generateMipmap: Tex image TEXTURE_CUBE_MAP_NEGATIVE_X level 0 is incurring lazy initialization.
WebGL warning: generateMipmap: Tex image TEXTURE_CUBE_MAP_POSITIVE_Y level 0 is incurring lazy initialization.
WebGL warning: generateMipmap: Tex image TEXTURE_CUBE_MAP_NEGATIVE_Y level 0 is incurring lazy initialization.
WebGL warning: generateMipmap: Tex image TEXTURE_CUBE_MAP_POSITIVE_Z level 0 is incurring lazy initialization.
WebGL warning: generateMipmap: Tex image TEXTURE_CUBE_MAP_NEGATIVE_Z level 0 is incurring lazy initialization.
XML Parsing Error: not well-formed
Location: http://digitalhumans.click/assets/character-assets/characters/adult_male/luke/luke.gltf
Line Number 1, Column 1: luke.gltf:1:1
An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page. audioEngine.js:131
The audio context is not running. Speech will not be able to be played until it is resumed. Use the "TextToSpeechFeature.resumeAudio" method to try to resume it after a user gesture. TextToSpeechFeature.js:42
`
No issue with your amplify version
Thanks
Tony

**Comment by Krxtopher** [comment]
Browsers won't allow microphone access if the site requesting access is not served over the `https://` protocol (using SSL). Your web server is not currently using SSL. If you want the demo to work on your server you will need to change your configuration so that you are serving the pages securely using SSL.

The specific web API we're using to request mic access is documented here if you want more details:  https://developer.mozilla.org/en-US/docs/Web/API/Navigator/mediaDevices

**Comment by anespo** [comment]
Thank you Kris.

**Comment by anespo** [comment]
Thank you, Kris. I fixed everything and now it works as you can see in my website.
Thank you for your help.
